# for_pc.yml
---
- hosts: localhost
  user: "{{ ubuntu_user }}"
  sudo: yes
  vars:
    ansible_sudo_pass: "{{ pass }}"

  tasks:
    - name: Update apt cache
      apt: update_cache=yes
      sudo: yes

    - name: Install required packages
      apt: name={{ item }}
      sudo: yes
      with_items:
        - mc
        - tree
        - htop

  roles:

    - role: chrome

    - role: rubymine
      rubymine_version: 2016.3.1

    - role: git
      git_packages:
        - git

    - role: terminator

    - role: ansible-postgresql-role
      pg_default_auth_method: 'md5'

    - role: nodejs

    - role: rvm
      become: true
      become_user: "{{ ubuntu_user }}"
      rvm1_rubies:
        - 'ruby-2.3.0'
      rvm1_bundler_install: True
      rvm1_user: "{{ ubuntu_user }}"

    - role: ansible-role-oh-my-zsh
      become: true
      become_user: "{{ ubuntu_user }}"
      users:
        - username: "{{ ubuntu_user }}"

    - role: ansible-skype-hubot
      skype_username: "{{ skype_username }}"
      skype_password: "{{ skype_password }}"

    - role: slack

########################################################
################## IT CAN BE INSTALED ##################
########################################################

#    - role: bundler

#    - role: redis
#      redis_port: 6777
#    - role: communication
